[workspace]
channels = ["conda-forge", "bioconda", "bioconda", "conda-forge"]
name = "head_model"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
mscorefonts = ">=0.0.1,<0.0.2"

[pypi-dependencies]
numpy = ">=2.3.5, <3"
chainer = ">=7.8.1, <8"
tables = ">=3.10.2, <4"
scikit-learn = ">=1.7.2, <2"
scipy = ">=1.16.3, <2"
xgboost = ">=3.1.1, <4"
pandas = ">=2.3.3, <3"
plotnine = ">=0.15.1, <0.16"
streamlit = ">=1.51.0, <2"
pyfonts = ">=1.1.3, <2"
seaborn = ">=0.13.2, <0.14"
black = ">=25.11.0, <26"
