[workspace]
channels = ["conda-forge", "bioconda", "bioconda", "conda-forge"]
name = "river-vis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
cmake = "*"
plotly = ">=6.5.0,<7"

[pypi-dependencies]
matplotlib = ">=3.10.7, <4"
plotnine = ">=0.15.1, <0.16"
pandas = ">=2.3.3, <3"
scipy = ">=1.16.3, <2"
streamlit = ">=1.51.0, <2"
pyfonts = ">=1.1.3, <2"
openpyxl = ">=3.1.5, <4"
seaborn = ">=0.13.2, <0.14"
black = ">=25.11.0, <26"
plotly = "*"
cufflinks = ">=0.17.3, <0.18"
